#!/usr/bin/env python
import argparse
import json 
import ..avalonbot


def send_email(subject, to_addresses,
               sender, #eg: "avutils-mail-sender@stanford.edu",
               smtp_server, #eg: "smtp.stanford.edu",
               contents=""):
    from email.mime.text import MIMEText
    import smtplib
    msg = MIMEText(contents)
    msg['Subject'] = subject
    msg['From'] = sender
    msg['To'] = ",".join(to_addresses)

    s = smtplib.SMTP(smtp_server)
    s.starttls();
    s.sendmail(sender, to_addresses, msg.as_string())
    s.quit()


def parse_config(json_config_file):
    parsed_config = json.loads(open(json_config_file).read()) 
    assert "players" in parsed_config, "Please specify a 'players' entry"
    assert "cards" in parsed_config, "Please specify a 'cards' entry"

    players = []
    for player_info in parse_config["players"]:
        assert "email" in player_info,\
            "All player entries must have 'email'; got: "+str(player_info) 
        assert "name" in player_info,\
            "All player entries must have 'name'; got: "+str(player_info) 
        players.append(avalonbot.game.Player(name=player_info["name"],
                                             email=player_info["email"])) 

    cards = []
    for card_type in parse_config["cards"]:
        cards.append(
         avalonbot.cards.card_type_to_cardclass[card_type]())

    return players, cards


def json_dump(obj):
    return json.dumps(obj, indent=4, separators=(',', ': '))


def run_game(args):
    players, cards = parse_config(args.json)
    game = avalonbot.game.Game(players=players, cards=cards) 
    game.assign_cards_to_players()

    secret_info = game.prepare_secret_info_to_tell_each_player() 
    card_types_info = game.prepare_info_on_cards_types()
    good_team_cards, bad_team_cards = game.prepare_info_on_teams()

    for player,private_info in secret_info.items():
        contents = """Hi """+player.name""",
Here is your avalon card assignment:
"""+json_dumps(private_info)+"""

Here is info on the cards present in this game:

Cards for the good team:
"""+json_dumps(good_team_cards)+"""

Cards for the bad team:
"""+json_dumps(bad_team_cards)+"""

Descriptions of each card:
"""+json_dumps(card_types_info)
        
        send_email(subject="Your Avalon Card Assignment",
                   to_addresses=[player.email],
                   sender="avalon-bot",
                   contents=contents) 


if __name__=="__main__":
    parser = argparse.ArgumentParser("Welcome to Avalon Bot!"
            +" I assume python 3 and access to an smtp server for sending mail")
    parser.add_argument("--smtp_server", required=True)
    parser.add_argument("--json_config_file", required=True,
                        help="See example config")
    args = parser.parse_args
    run_game(args)
    
